name: "Free Azure Deploy - Flask via Terraform + GHCR"

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Give Actions permission to push images to GHCR
permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: flask-app
  IMAGE_TAG: latest

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Login to Azure using JSON credentials"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Set up Terraform"
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.5

      - name: "Convert GitHub username to lowercase"
        id: lowername
        run: echo "LOWER_USER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: "Build Docker image"
        run: |
          docker build -t ghcr.io/${{ env.LOWER_USER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

      - name: "Login to GHCR"
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: "Push Docker image to GHCR"
        run: |
          docker push ghcr.io/${{ env.LOWER_USER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: "Terraform Init & Apply (Deploy to Free Tier App Service)"
        run: |
          terraform init -input=false
          terraform apply -auto-approve -input=false
